"""
Django settings for perswebsite project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', "django-insecure-t5ym%&y&v)qqel)vyt(495g$vc2zqj#e=()z)h7v^*hm0xsyzu")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'False').lower() == 'true'

# Updated ALLOWED_HOSTS for Railway deployment
ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'web-production-7840.up.railway.app']
CSRF_TRUSTED_ORIGINS = [
    'https://web-production-7840.up.railway.app',
    'http://web-production-7840.up.railway.app',
]

if not DEBUG:
    # Add Railway domain when deployed
    RAILWAY_STATIC_URL = os.getenv('RAILWAY_STATIC_URL')
    if RAILWAY_STATIC_URL:
        ALLOWED_HOSTS.append(RAILWAY_STATIC_URL)

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'django_summernote',
    'myapp.apps.MyappConfig',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Add WhiteNoise for static files
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "perswebsite.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates']
        ,
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "perswebsite.wsgi.application"

# Database configuration for Railway
if 'DATABASE_URL' in os.environ:
    # Production database (Railway PostgreSQL)
    DATABASES = {
        'default': dj_database_url.parse(os.environ.get('DATABASE_URL'))
    }
else:
    # Local development database
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# WhiteNoise static files configuration for Railway
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Security settings for production
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ===== SUMMERNOTE CONFIGURATION FOR CODE SUPPORT =====
SUMMERNOTE_THEME = 'bs4'
SUMMERNOTE_CONFIG = {
    'iframe': True,
    'summernote': {
        'airMode': False,
        'width': '100%',
        'height': '500',
        'lang': 'en-US',
        'toolbar': [
            ['style', ['style']],
            ['font', ['bold', 'italic', 'underline', 'strikethrough', 'superscript', 'subscript', 'clear']],
            ['fontname', ['fontname']],
            ['fontsize', ['fontsize']],
            ['color', ['color']],
            ['para', ['ul', 'ol', 'paragraph']],
            ['height', ['height']],
            ['table', ['table']],
            ['insert', ['link', 'picture', 'video', 'hr']],
            ['view', ['fullscreen', 'codeview']],
            ['help', ['help']],
            ['misc', ['codeblock']],  # Code block button
        ],
        'codeblock': {
            'languages': [
                {'name': 'Python', 'value': 'python'},
                {'name': 'JavaScript', 'value': 'javascript'},
                {'name': 'HTML', 'value': 'html'},
                {'name': 'CSS', 'value': 'css'},
                {'name': 'SQL', 'value': 'sql'},
                {'name': 'Bash/Shell', 'value': 'bash'},
                {'name': 'JSON', 'value': 'json'},
                {'name': 'XML', 'value': 'xml'},
                {'name': 'Django Template', 'value': 'django'},
                {'name': 'YAML', 'value': 'yaml'},
                {'name': 'Markdown', 'value': 'markdown'},
                {'name': 'PHP', 'value': 'php'},
                {'name': 'Java', 'value': 'java'},
                {'name': 'C++', 'value': 'cpp'},
                {'name': 'C', 'value': 'c'},
                {'name': 'Go', 'value': 'go'},
                {'name': 'Rust', 'value': 'rust'},
                {'name': 'TypeScript', 'value': 'typescript'},
            ]
        },
        'codemirror': {
            'theme': 'monokai',
            'lineNumbers': True,
            'lineWrapping': True,
            'styleActiveLine': True,
            'matchBrackets': True,
            'autoCloseBrackets': True,
            'indentUnit': 4,
        }
    },
    'css': (
        '//cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.0/codemirror.min.css',
        '//cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.0/theme/monokai.min.css',
        '//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.3.1/styles/github-dark.min.css',
    ),
    'js': (
        '//cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.0/codemirror.min.js',
        '//cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.0/mode/python/python.min.js',
        '//cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.0/mode/javascript/javascript.min.js',
        '//cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.0/mode/xml/xml.min.js',
        '//cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.0/mode/css/css.min.js',
        '//cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.0/mode/sql/sql.min.js',
        '//cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.0/mode/shell/shell.min.js',
        '//cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.0/mode/yaml/yaml.min.js',
        '//cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.0/mode/php/php.min.js',
        '//cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.0/mode/clike/clike.min.js',
        '//cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.0/mode/go/go.min.js',
        '//cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.0/mode/rust/rust.min.js',
    ),
    'lazy': False,
}

# Optional: Configure media files for Summernote uploads
SUMMERNOTE_UPLOAD_TO = 'uploads/'
SUMMERNOTE_STORAGE_CLASS = 'django.core.files.storage.FileSystemStorage'

# Security settings for file uploads (optional but recommended)
SUMMERNOTE_UPLOAD_ALLOWED_FILETYPES = ['image']
SUMMERNOTE_MAX_FILE_SIZE = 5 * 1024 * 1024  # 5MB