# Generated by Django 5.2.4 on 2025-07-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bibtex_entry', models.TextField()),
                ('featured', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('authors', models.CharField(blank=True, max_length=1000)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('journal', models.CharField(blank=True, max_length=300)),
                ('booktitle', models.CharField(blank=True, max_length=300)),
                ('organization', models.CharField(blank=True, max_length=300)),
                ('publisher', models.CharField(blank=True, max_length=200)),
                ('pages', models.CharField(blank=True, max_length=50)),
                ('volume', models.CharField(blank=True, max_length=20)),
                ('number', models.CharField(blank=True, max_length=20)),
                ('doi', models.CharField(blank=True, max_length=100)),
                ('url', models.URLField(blank=True)),
                ('abstract', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year', 'title'],
            },
        ),
    ]
