# Generated by Django 5.2.4 on 2025-07-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='citation_count',
            field=models.IntegerField(default=0, help_text='Number of citations from Google Scholar'),
        ),
        migrations.AddField(
            model_name='publication',
            name='last_citation_update',
            field=models.DateTimeField(blank=True, help_text='When citations were last updated', null=True),
        ),
    ]
