# Generated by Django 5.2.4 on 2025-07-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_tag_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('start_year', models.CharField(help_text="e.g., '2018'", max_length=10)),
                ('end_year', models.CharField(help_text="e.g., '2021'", max_length=10)),
                ('description', models.TextField(blank=True, help_text='Optional description or thesis title')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in timeline (0 = most recent)')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biography_title', models.CharField(default='Biography', max_length=100)),
                ('biography_content', models.TextField(help_text="Main biography text. You can use HTML tags for formatting like <span class='highlight'>text</span>")),
                ('email', models.EmailField(default='faroukyahayaco@gmail.com', max_length=254)),
                ('phone', models.CharField(default='+33 66 6 69 69 19', max_length=20)),
                ('address', models.TextField(default='37 cours de Quebec\nBordeaux, France')),
                ('research_interests_title', models.CharField(default='Research Interests', max_length=100)),
                ('research_interests_content', models.TextField(default='Inverse filtering, Source Separation, Array signal processing, High-dimensional data analysis, Matrix/Tensor decomposition, Compressive learning, Randomized methods, Sensor calibration, Low-rank approximations, Medical image analysis (2D MRI, fMRI modalities)')),
                ('linkedin_url', models.URLField(blank=True, default='https://fr.linkedin.com/in/faroya')),
                ('scholar_url', models.URLField(blank=True, default='https://scholar.google.com/citations?user=p8zrh5gAAAAJ&hl=en')),
                ('orcid_url', models.URLField(blank=True, default='https://orcid.org/0000-0003-4147-2453')),
                ('researchgate_url', models.URLField(blank=True, default='https://www.researchgate.net/profile/Farouk-Yahaya')),
                ('github_url', models.URLField(blank=True, default='https://github.com/FaroukYahaya')),
                ('experience_title', models.CharField(default='Professional Experience', max_length=100)),
                ('show_experience', models.BooleanField(default=True, help_text='Show/hide the professional experience section')),
                ('education_title', models.CharField(default='Education', max_length=100)),
                ('show_education', models.BooleanField(default=True, help_text='Show/hide the education section')),
                ('news_title', models.CharField(default='Latest News', max_length=100)),
                ('show_news', models.BooleanField(default=True, help_text='Show/hide the latest news section')),
                ('news_count', models.PositiveIntegerField(default=3, help_text='Number of latest posts to show')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Page',
                'verbose_name_plural': 'Home Page',
            },
        ),
        migrations.CreateModel(
            name='ProfessionalExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('start_date', models.CharField(help_text="e.g., 'Feb 2024', 'Jul 2022'", max_length=20)),
                ('end_date', models.CharField(help_text="e.g., 'Present', 'Jan 2024'", max_length=20)),
                ('description', models.TextField(blank=True, help_text='Optional description of the role')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in timeline (0 = most recent)')),
            ],
            options={
                'verbose_name': 'Professional Experience',
                'verbose_name_plural': 'Professional Experiences',
                'ordering': ['order'],
            },
        ),
    ]
