# Generated by Django 5.2.4 on 2025-07-21 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_education_homepage_professionalexperience'),
    ]

    operations = [
    ]
