# Generated by Django 5.2.4 on 2025-07-21 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20250721_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(default='Teaching', max_length=100)),
                ('introduction', models.TextField(default='I enjoy teaching computer science and AI concepts, from basic programming to advanced machine learning. My approach focuses on practical learning and real-world applications.', help_text='Main introduction text for the teaching page')),
                ('show_statistics', models.BooleanField(default=True, help_text='Show teaching statistics')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Teaching Page',
                'verbose_name_plural': 'Teaching Page',
            },
        ),
        migrations.CreateModel(
            name='TeachingStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_type', models.CharField(choices=[('total_courses', 'Total Courses Taught'), ('total_students', 'Total Students Taught'), ('total_hours', 'Total Teaching Hours'), ('years_experience', 'Years of Teaching Experience')], max_length=20, unique=True)),
                ('value', models.CharField(help_text="e.g., '15', '500+', '3 years'", max_length=20)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('show_on_page', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'stat_type'],
            },
        ),
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_start', models.IntegerField(help_text='Starting year (e.g., 2021)')),
                ('year_end', models.IntegerField(help_text='Ending year (e.g., 2022)')),
                ('description', models.TextField(blank=True, help_text='Optional description for this academic year')),
                ('is_active', models.BooleanField(default=True, help_text='Show this academic year on the page')),
            ],
            options={
                'ordering': ['-year_start'],
                'unique_together': {('year_start', 'year_end')},
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('credits', models.CharField(blank=True, help_text="e.g., '3 ECTS'", max_length=20)),
                ('description', models.TextField(blank=True, help_text='Course description')),
                ('semester', models.CharField(choices=[('1', 'Semester 1'), ('2', 'Semester 2'), ('full', 'Full Year'), ('other', 'Other')], default='1', max_length=10)),
                ('institution', models.CharField(choices=[('ULCO', 'ULCO'), ('EIL', 'EIL'), ('IUT', 'IUT'), ('other', 'Other')], default='ULCO', max_length=50)),
                ('custom_institution', models.CharField(blank=True, help_text="If 'Other' is selected above", max_length=100)),
                ('hours_per_week', models.DecimalField(blank=True, decimal_places=1, help_text='Hours per week', max_digits=4, null=True)),
                ('total_hours', models.IntegerField(blank=True, help_text='Total hours for the course', null=True)),
                ('student_count', models.IntegerField(blank=True, help_text='Number of students', null=True)),
                ('co_teachers', models.CharField(blank=True, help_text="Co-teachers (e.g., 'A. Ahmad')", max_length=200)),
                ('topics_covered', models.TextField(blank=True, help_text='Main topics covered (comma-separated)')),
                ('technologies_used', models.CharField(blank=True, help_text="Technologies/tools used (e.g., 'Python, scikit-learn')", max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order within semester (0 = first)')),
                ('is_featured', models.BooleanField(default=False, help_text='Highlight this course')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='myapp.academicyear')),
            ],
            options={
                'ordering': ['academic_year', 'semester', 'order', 'title'],
            },
        ),
    ]
